# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9cdec5713189752fbf0d55109ac3a92f6761289601d7a0685fd3f8185264589e5fa9855c7f613a288c99d2e7355fdbf9ff397d6deae80417859773db636a9e4

test:
  secret_key_base: d2b8ac4593a401652c7e6520f401e28b97071d6809c566904fcfdcc11ee56c019f76978bc9d942f8bf9ee3e5aabda0cca8bd59b1b08fc4f7cd46446c5c9d2425

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
